plugins {
    id 'java'
}

group = 'org.example'
version = 'unspecified'

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile) {
    options.compilerArgs.addAll([
        '--add-exports', 'jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED',
        '--add-exports', 'jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED'
    ])
}

dependencies {
    implementation "org.scijava:parsington:3.0.0"
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}