stateDiagram-v2
    direction LR

    home --> scorePosition : when complete and ((someCond()) || (!someCond()))
    scoring --> scorePosition : when complete and ((someCond()) || (!someCond()))

    classDef initialState color:#00FF00
    class home initialState